spring.application.name=StudentManager

server.port=9090

server.error.include-message=always

server.servlet.context-path=/app

logging.level.org.springframework=info
logging.level.com.pioneers=debug
